### ISSUE TITLE
Reasoning over ontology versions

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#16]
Make older versions of an ontology available to the AberOWL API on request so that they can be queried. Keep the classified version of the ontology for a certain duration (or the duration of a session) so that it will not have to be reclassified, but make sure that the classified version is discarded after a while.

**Comment by debuos512** [comment]
Mainly a problem of https://github.com/bio-ontology-research-group/AberOWL

Maybe a 'version' parameter of runQuery which classifies ondemand if not loaded, could pass unix time of version or incremental number id (though currently keyed by unix time), and get ID from site

**Comment by leechuck** [comment]
Done by @MiguelAngelRG
