### ISSUE TITLE
URI translation layer on front-end

### ISSUE THREAD

**Issue by debuos512** [bio-ontology-research-group/aberowl-orepo#17]
To follow https://github.com/bio-ontology-research-group/AberOWL/issues/1

**Comment by reality** [comment]
Here is an example of the cool box thing http://www.devthought.com/wp-content/projects/jquery/textboxlist/Demo/

**Comment by debuos512** [comment]
RELEVANT https://github.com/xoxco/jQuery-Tags-Input/pull/229

**Comment by debuos512** [comment]
The only thing left is adding support for AND, SOME and such

**Comment by debuos512** [comment]
Other keywords:

description ::= conjunction 'or' conjunction { 'or' conjunction }
         | conjunction
conjunction ::= classIRI 'that' [ 'not' ] restriction { 'and' [ 'not' ] restriction }
         | primary 'and' primary { 'and' primary }
         | primary
primary ::= [ 'not' ](restriction | atomic)
restriction ::= objectPropertyExpression 'some' primary
         | objectPropertyExpression 'only' primary
         | objectPropertyExpression 'value' individual
         | objectPropertyExpression 'Self'
         | objectPropertyExpression 'min' nonNegativeInteger [ primary ]
         | objectPropertyExpression 'max' nonNegativeInteger [ primary ]
         | objectPropertyExpression 'exactly' nonNegativeInteger [ primary ]
         | dataPropertyExpression 'some' dataPrimary
         | dataPropertyExpression 'only' dataPrimary
         | dataPropertyExpression 'value' literal
         | dataPropertyExpression 'min' nonNegativeInteger [ dataPrimary ]
         | dataPropertyExpression 'max' nonNegativeInteger [ dataPrimary ]
         | dataPropertyExpression 'exactly' nonNegativeInteger [ dataPrimary ]
atomic ::= classIRI
         | '{' individualList '}'  
         | '(' description ')'
