### ISSUE TITLE
make autocompletion work for multi-word terms

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#18]
Autocompletion should work for terms that contain a space, such as 'pancreas development'.

**Comment by debuos512** [comment]
'pancreas development' works for me at http://aber-owl.net/aber-owl/new/

**Comment by leechuck** [comment]
Ok, 'organ section' will result in completions first for "organ", then when "section" is typed also for all other things containing "section". It should just show completion for things that contain both organ and section (not necessarily in this order), so a conjunctive query would be better.

**Comment by debuos512** [comment]
Pretty sure this is done. Please re-open if it is not right
