### ISSUE TITLE
Simple class search on front page

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#3]
Add a simple text-based class search to the front page. The results should list matching ontologies, classes, and - if only one class matches or if one of many matching classes is selected - the complete information on this class.

**Comment by debuos512** [comment]
Should this replace the Manchester OWL Syntax search?

**Comment by leechuck** [comment]
No, it should be in addition to the Manchester search. It could use a new input field, or just reuse the existing one (there could be a text field which shows the class description after every successful autocompletion).

**Comment by leechuck** [comment]
There could be some smart interaction with the tags, like, click on a tag and show class info below. Also, default to show class info if there's only one class.

Need to add info to Lucene index.

**Comment by leechuck** [comment]
At some point, this needs to link to #21 for metadata.
