### ISSUE TITLE
Show tags in overview of ontologies

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#30]
Add the tags to the ontology overview (Browse)

**Comment by leechuck** [comment]
Tags like "Classfied", "Unloadable", etc.

**Comment by debuos512** [comment]
this will require a new api route to get load status of all ontologies in
one go

On 21 May 2015 at 11:42, Robert Hoehndorf notifications@github.com wrote:

> Tags like "Classfied", "Unloadable", etc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bio-ontology-research-group/aberowl-orepo/issues/30#issuecomment-104222516
> .

## 

Luke Slater
:O)
