### ISSUE TITLE
Identify 'obsolete' classes and hide in browse

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#39]
Alternatively, show the obsolete classes in grayish shade at the bottom.

Also, hide them from visualize, if possible.

For comparison, have a look at FYPO in BioPortal; it hides all the obsolete classes (they have an annotation property marking them as 'obsolete', or 'deprecated' in OWL). Normally, these classes appear directly under owl:Thing, which messes up the treeview and visualization.

**Comment by debuos512** [comment]
They are just hidden for now, I think greying them out or so can be 0.3?

**Comment by leechuck** [comment]
Yes.
