### ISSUE TITLE
Add SPARQL and PubMed search as a 'tab' in the ontology overview

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#41]
Like on front page, just make available for each ontology, in a tab.

**Comment by debuos512** [comment]
This is not very minor, because the PubMed search page seems to be generated by a Groovy script, it would need to be ported / script changed to give JSON response for AJAX use (same for SPARQL too I think)

**Comment by leechuck** [comment]
The API gives a json response, more or less. You have to pass type=json
or something like that.

**Comment by leechuck** [comment]
Actually, the option is "output=json"
