### ISSUE TITLE
Add URI to autocomplete search

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#44]
Some ontologies don't use labels, e.g., APATREATMENT. The autocomplete does not work at all for these ontologies, so you cannot query. Solution would be to add the URI to the autocomplete, or at least the string after the last occurrence of "#" or "/" (preference for "#").

**Comment by debuos512** [comment]
Added URI fragment for now https://github.com/bio-ontology-research-group/AberOWL/commit/6be431c23b919d7f75114934f8c7cec288193f1e
