### ISSUE TITLE
Strange behavior of treeview

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#45]
There seems to be a slightly hard to reproduce bug in the treeview. To try to reproduce:
Unfold 1 class with many subclasses.
Then unfold three classes on the same level.
Unfold some classes below and close again.

What happens is that if you open and close a subclass of the last one, sometimes the last unfolded class above disappears.

A possibly related bug: if you quickly open and close subclasses, the treeview breaks entirely in that it does not respond any longer to queries.

**Comment by debuos512** [comment]
a2dismod mod-evasive20
service apache2 restart

fixes rate thing
