### ISSUE TITLE
Simple class search in treeview

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#48]
Would it be possible to add a simple class search, with autocomplete, just above the treeview, which allows jumping straight to the class in the treeview browser?

**Comment by leechuck** [comment]
Please also remove scrollbars from textbox.

**Comment by debuos512** [comment]
there are no scrollbars for me. what browser are you using?

**Comment by leechuck** [comment]
Chromium. There are scroll bars on the query box too.

> there are no scrollbars for me. what browser are you using?  — Reply
> to this email directly or view it on GitHub.
