### ISSUE TITLE
New front page

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#69]
Have simple search box that only searches for label matches.

Show results of match, with matching ontologies as facets (left).

Add tab to search for Class, Ontology, PubMed, Resource.

In Ontology tab, search for ontology matching the query.

Move current Query to "advanced search".

**Comment by leechuck** [comment]
Elaborating a bit on that:

The query box at the front page should be able to search for textual matches as well as for Manchester OWL queries. At the moment, the search box is a bit complicated, and a simpler search would be better. The results should be displayed as a table with faceted filters (select boxes). The filters should be:
- ontology (exclude/include results in which the ontology name or description matches; link goes to the ontology)
- class (exclude/include results in which the label/description of the class matches; link goes to the class in the ontology)

The "class" tab could have sub-facets (label, description, axiom search).

**Comment by leechuck** [comment]
Also see https://github.com/bio-ontology-research-group/aberowl-orepo/issues/70

**Comment by KeironO** [comment]
Maybe we can do what @MiguelAngelRG suggested, and follow popular search engines.

![IMAGE](http://i.imgur.com/K6xSRLK.png)

**Comment by debuos512** [comment]
But as discussed previously this does not communicate what Aber owl is or
does, doesn't link to a login register browse upload or to the list of
ontologies... This is a specific application, not just a Web search and as
such it needs some more information, however nice it is to just have a box

**Comment by MiguelAngelRG** [comment]
I think that it would be worthy to discuss at the meeting .. because in order to communicate what Aber OWL is  we have a help page that contains specific information about what project Aber-OWL is.
