### ISSUE TITLE
limited functionality tree browse with entity hyperlink

### ISSUE THREAD

**Issue by micheldumontier** [bio-ontology-research-group/aberowl-orepo#80]
Using a class hyperlink (e.g. [1]) causes the tree to only expand to that concept - which is clean - but unfortunately, does not also show the children of the classes in the parent lineage. The only way to do this is to expand those nodes, but then you lose the place with the current concept.  might be worth taking a survey to see whether this functionality is sufficient or intuitive for that matter.

[1] http://aber-owl.net/ontology/SIO#!http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_010004

**Comment by leechuck** [comment]
What do you think the desired behavior should be? Fully expand the tree, including the children of the selected node, and just highlight?

**Comment by micheldumontier** [comment]
I think you want the children of each parent node in the true path to appear by default

**Comment by leechuck** [comment]
Understood. Will be done.

**Comment by leechuck** [comment]
Done.

**Comment by micheldumontier** [comment]
very nice :+1:
