### ISSUE TITLE
Date format broken

### ISSUE THREAD

**Issue by leechuck** [bio-ontology-research-group/aberowl-orepo#96]
Sometimes, the date format of ontologies uplaoded is broken. For example, see the PO, latest submission shows "Tue, 01 Jan 47856 12:44:08 GMT" (very far in the future).

**Comment by debuos512** [comment]
fixed in https://github.com/bio-ontology-research-group/aberowl-orepo/commit/b50b6b164dc4f89702f4cdb7c423ca420b830dac

**Comment by debuos512** [comment]
and fixed PO latest release manually. if it needs to be done for other submissions anywhere you just need to download it by 1000 (also do it for lastSubDate)
